### ISSUE TITLE
Can't reproduce TESSreduce analysis with a newer version of the code

### ISSUE THREAD

**Issue by kirxkirx** [CheerfulUser/TESSreduce#14]
After installing TESSreduce (with `pip install git+https://github.com/CheerfulUser/TESSreduce.git`) to a new conda environment I realized that I can't reproduce the lightcurve I made with TESSreduce about a year ago. I still have the old TESSreduce installation in the old environment and it re-created the lightcurve with no issues. The lightcurve is that of the galactic nova V606 Vul in TESS Sector 41 discussed in [this e-print](https://arxiv.org/abs/2311.04903). 

This is how the lightcurve is supposed to look like 
![v606vul_old](https://github.com/CheerfulUser/TESSreduce/assets/42295873/5788ca88-2c54-481d-a926-694e6e1730f6)
and this is how it looks with the newer version of the code (the lightcurve is flat and the diagnostic image looks weird - like there is a narrow vertical strip/slit through which one can see the target and other stars while the rest of the image is blank):
![v606vul_new](https://github.com/CheerfulUser/TESSreduce/assets/42295873/f290f7c6-b71b-41e3-9e8f-6dde20a63ea6)
In both cases, the analysis code is simply
````
import tessreduce as tr
ra = 305.2820958
dec = +29.2359028
sector = 41
tess = tr.tessreduce(ra=ra,dec=dec,sector=sector)
tess.reduce()
tess.plotter()
````
The detailed output may be found in the Jupyter notebooks: old [V606_vul_tr-rerun.ipynb.gz](https://github.com/CheerfulUser/TESSreduce/files/15367231/V606_vul_tr-rerun.ipynb.gz) and new [V606_vul_tr-rerun__teq_new_tr.ipynb.gz](https://github.com/CheerfulUser/TESSreduce/files/15367232/V606_vul_tr-rerun__teq_new_tr.ipynb.gz)

Silly enough, I don't know how to find the exact version number of TESSreduce that I've installed via pip. The only thing I could come up with to point the exact versions of the code that I'm using is to extract a copy of TESSreduce code from conda directories: old TESSreduce [tessreduce_old_version_that_works.zip](https://github.com/CheerfulUser/TESSreduce/files/15367237/tessreduce_old_version_that_works.zip) and new TESSreduce [tessreduce_new_version_that_fails.zip](https://github.com/CheerfulUser/TESSreduce/files/15367238/tessreduce_new_version_that_fails.zip)

So the questions, I guess, are: what am I doing wrong and how do I reproduce the nova lightcurve with the current version of TESSreduce?

**Comment by CheerfulUser** [comment]
Thanks for picking this up! I think the problem here is that it changed to run the reduction by default, so calling the reduction again is producing junk. I've updated the readme to reflect that. Can you try it again using the new format and let me know how it goes?

**Comment by kirxkirx** [comment]
Thank you very much for your help!
Yes, removing the `tess.reduce()` step from the analysis script produces the expected results with the current version of TESSreduce:

````
import tessreduce as tr
ra = 305.2820958
dec = +29.2359028
sector = 41
tess = tr.tessreduce(ra=ra,dec=dec,sector=sector)
#tess.reduce()
tess.plotter()
````
![tr_crop](https://github.com/user-attachments/assets/e8c93d60-4cdf-4df1-b966-c99eeee07800)
