### ISSUE TITLE
sn_lookup() fails on 2019gak

### ISSUE THREAD

**Issue by lcgordon** [CheerfulUser/TESSreduce#7]
Hey - I'm trying to pull some light curves and sn_lookup() spits the following error when given 2019gak: 

```
tr.sn_lookup("2019gak")
Traceback (most recent call last):

  Input In [14] in <cell line: 1>
    tr.sn_lookup("2019gak")

  File ~/opt/anaconda3/envs/urop2/lib/python3.9/site-packages/tessreduce/tessreduce.py:493 in sn_lookup
    covers += [cover]

UnboundLocalError: local variable 'cover' referenced before assignment
```

As far as I can tell this is an issue of the immediately preceding if/else if statement assigning the variable 'cover' within its branches but not having a regular else clause. This is the only SN I've come across so far to hit this specific issue.

**Comment by CheerfulUser** [comment]
Thanks for spotting this! I've just fixed this edge case.
